name: check availability

on:
  schedule:
    - cron: "0,15 * * * *"
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.2", "8.3"]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer require devium/toml
